In [1]:
import numpy as np

In [3]:
mTransicao = np.matrix([[0.7,0.15,0.15],[0.2,0.8,0.15],[0.1,0.05,0.7]])
print(mTransicao)

[[0.7  0.15 0.15]
 [0.2  0.8  0.15]
 [0.1  0.05 0.7 ]]


In [8]:
vInicial = np.matrix([[0.2325],[0.2875],[0.48]])
print(vInicial)

[[0.2325]
 [0.2875]
 [0.48  ]]


In [11]:
vProximo = np.matmul(mTransicao,vInicial)

In [12]:
vProximo

matrix([[0.277875],
        [0.3485  ],
        [0.373625]])

In [20]:
for k in range(1,16,1):
  vProximo = np.matmul(mTransicao,vInicial)
  vInicial = vProximo
  print(vProximo)
  print("\n\n")

[[0.33332944]
 [0.47603462]
 [0.19063594]]



[[0.33333119]
 [0.47608897]
 [0.19057983]]



[[0.33333216]
 [0.47612439]
 [0.19054345]]



[[0.33333269]
 [0.47614746]
 [0.19051985]]



[[0.33333298]
 [0.47616248]
 [0.19050454]]



[[0.33333314]
 [0.47617226]
 [0.1904946 ]]



[[0.33333323]
 [0.47617863]
 [0.19048815]]



[[0.33333327]
 [0.47618277]
 [0.19048396]]



[[0.3333333 ]
 [0.47618546]
 [0.19048124]]



[[0.33333332]
 [0.47618722]
 [0.19047947]]



[[0.33333332]
 [0.47618836]
 [0.19047832]]



[[0.33333333]
 [0.4761891 ]
 [0.19047757]]



[[0.33333333]
 [0.47618958]
 [0.19047709]]



[[0.33333333]
 [0.47618989]
 [0.19047677]]



[[0.33333333]
 [0.4761901 ]
 [0.19047657]]



